Repository harilvfs/carch, pull requests merged in 2024-11, with the labels that each got.

#25 Docs Light/Dark Mode Switcher
  docs/index.md
  docs/script.js
  docs/style.css
Labels: wontfix

#26 Add Option to Install Music Packages in Package Script
  scripts/Install Packages.sh
Labels: enhancement, Bash

#27 Remove Reddit Badge From README.md
  README.md
Labels: bug, invalid

#28 Add Spotify to Music Packages
  scripts/Install Packages.sh
Labels: enhancement, Bash

#29 Add more essential packages to installation script
  scripts/Install Packages.sh
Labels: enhancement, Bash

#30 Remove Script Zip File
  .gitignore
Labels: enhancement

#31 Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#32 Update Completed Roadmap Tasks On Carch
  .github/roadmap.md
Labels: enhancement

#33 Add Tor Browser Installation into Packages Installation Script
  scripts/Install Packages.sh
Labels: enhancement, Bash

#35 Path Define To CarchScripts Zip Dir
  .github/workflows/zip.yml
Labels: enhancement, Workflow

#36 Binary Build Script Fixes
  binarybuild.sh
  build/carch
Labels: enhancement, Bash, Fix Script

#38 Package Installation & Menu Script Refactor
  scripts/Alacritty.sh
  scripts/Aur.sh
  scripts/Dwm.sh
  scripts/Fastfetch.sh
  scripts/Fonts.sh
  scripts/Grub.sh
  scripts/Hyprland.sh
  scripts/Install Packages.sh
  scripts/Kitty.sh
  scripts/LTS-Kernal.sh
  scripts/Neovim.sh
  scripts/Packages.sh
  scripts/Picom.sh
  scripts/Rofi.sh
  scripts/Sddm.sh
  scripts/SwayWM.sh
  scripts/Themes-Icons.sh
  scripts/i3wm.sh
Labels: Bash, Refactor

#39 Add Gum Interactive Menus and Confirmation to Setup Scripts
  scripts/Dwm Setup.sh
  scripts/Hyprland Setup.sh
  scripts/Install Fonts.sh
  scripts/Install LTS Kernal.sh
  scripts/Setup Alacritty.sh
  scripts/Setup Aur.sh
  scripts/Setup Fastfetch.sh
  scripts/Setup GRUB.sh
  scripts/Setup Kitty.sh
  scripts/Setup Neovim.sh
  scripts/Setup Picom.sh
  scripts/Setup Rofi.sh
  scripts/Setup SDDM.sh
  scripts/Setup Themes-Icons.sh
  scripts/SwayWM Setup.sh
  scripts/Wallpapers.sh
  scripts/i3wm Setup.sh
Labels: enhancement, Menu Changes, UI, Refactor

#41 Package Installation & Menu Script Refactor
  scripts/Packages.sh
Labels: enhancement, Bash, Refactor

#42 Update Carch Scripts Zip With Latest Changes
  zip/carchscripts.zip
Labels: Zip

#44 Remove Echo On Running Script
  cxfs.sh
Labels: UI, Fix Script

#45 Add a tag for netflix unoffical package
  scripts/Packages.sh
Labels: enhancement, Bash

#46 Update CXFS Figlet Heading to Carch
  cxfs.sh
Labels: Menu Changes, UI, Fix Script

#47 Update Carch Preview to Reflect Latest Script Changes
  README.md
  docs/index.md
  preview/carchv3.0.gif
Labels: Readme/Preview, Markdown

#48 Add 'Back to Top' Navigation Links in README.md
  README.md
Labels: Readme/Preview

#49 Add Contributor Metrics to Carch
  .github/workflows/contributors.yml
Labels: Workflow

#50 Add Wallpaper Credits to Script and Fix README Placement
  README.md
  scripts/Wallpapers.sh
Labels: Readme/Preview, Bash

#52 Update Carch script zip to reference the latest commit
  zip/carchscripts.zip
Labels: Zip

#54 Update Carch script ZIP to latest commit version
  zip/carchscripts.zip
Labels: Zip

#56 Update cxfs script for version 3.0.7
  cxfs.sh
Labels: enhancement, UI

#58 Refac Sddm Script Heading
  scripts/Sddm.sh
Labels: enhancement, UI, Refactor

#59 Update carch script ZIP to latest commit
  zip/carchscripts.zip
Labels: Zip

#60 Add script zip checklist to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, Markdown

#63 Update Carch Script Zip with Latest Changes
  zip/carchscripts.zip
Labels: Zip

#64 Rebase Carch structure for cleaner design
  .gitignore
  build/binarybuild.sh
  run/clean.sh
  setup/run.sh
  setup/setup.sh
Labels: enhancement, Refactor

#65 Rebase Carch Package Build Structure
  package.json
Labels: enhancement, Refactor

#66 Rename 'setup' to 'install'
  install/run.sh
  install/setup.sh
Labels: enhancement, Refactor

#67 Change Image Extension to .webp Format
  README.md
  preview/arch.webp
  preview/archx.webp
  preview/bash.png
  preview/linux.png
  preview/package.png
Labels: enhancement, Readme/Preview

#68 Fix Image Source Links in README
  README.md
Labels: Readme/Preview

#69 Clarify README text for better understanding
  scripts/README
  scripts/README.txt
Labels: Readme/Preview

#70 Review and Refine Template
  .github/ISSUE_TEMPLATE.md
  .github/ROADMAP.md
Labels: documentation

#71 Fix Roadmap Link
  README.md
  docs/index.md
Labels: documentation, Readme/Preview

#72 Rename and Restructure CXFS to Core
  core.sh
  install/run.sh
  run/cleanrun.sh
Labels: enhancement, Bash, Refactor

#73 Update package to latest structure
  package.json
Labels: enhancement

#74 Fix .gitignore directory handling and update README badges
  .gitignore
  README.md
Labels: enhancement, Readme/Preview, Markdown

#75 Add essential packages to the package script.
  scripts/Packages.sh
Labels: Bash

#76 Refine PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Markdown

#77 Update Carch ZIP to the latest commit
  zip/carchscripts.zip
Labels: Zip

#78 Remove unnecessary badges from README
  README.md
Labels: Readme/Preview

#79 Remove discord chat badges from README
  README.md
Labels: Readme/Preview

#80 Remove Installation Guide from README
  README.md
Labels: Readme/Preview

#81 Update Folder Structure to Align with bin Convention
  bin/clean.sh
  bin/cleanrun.sh
Labels: Refactor

#82 Rename preview to source for Better Alignment
  source/arch.webp
  source/archx.webp
  source/carch.gif
  source/carchv3.0.gif
  source/penguin.webp
Labels: enhancement

#83 Move ZIP to source Directory
  .github/workflows/zip.yml
  source/zip/carchscripts.zip
Labels: enhancement, Workflow

#84 Update PKGBUILD for AUR Package
  PKGBUILD
Labels: enhancement, Refactor

#85 Add AUR installation method to the guide
  .github/INSTALLATION.md
Labels: documentation, enhancement

#87 Add AUR package version badge to Carch
  .github/INSTALLATION.md
  README.md
  docs/index.md
Labels: documentation, Readme/Preview

#88 Add GitHub logo to README badges
  README.md
Labels: Readme/Preview

#89 Update GitHub badge logo color to black
  README.md
Labels: Readme/Preview

#92 Remove 'Inspiration' tag
  README.md
Labels: documentation

#93 Change from bin to git package in AUR
  PKGBUILD
Labels: bug, enhancement

#94 Refind imgshield badges
  README.md
Labels: Readme/Preview

#96 Add carch-gtk Setup Script
  carch-gtk.py
Labels: enhancement, UI, Refactor

#97 Add GUI/GTK Check Box Completion
  .github/ROADMAP.md
Labels: documentation

#98 Add Yazi File Manager to Package Script
  scripts/Packages.sh
Labels: enhancement, Bash

#99 Add GTK Installation Guide to Documentation
  .github/INSTALLATION.md
  docs/index.md
Labels: documentation

#100 Fix Image Source Link in Documentation
  docs/assets/arrowdown.webp
  docs/index.md
Labels: documentation

#101 Refine Roadmap, README, and Documentation
  .github/ROADMAP.md
  README.md
Labels: documentation, Readme/Preview

#104 Fix: Mobile Side View on Documentation Website
  docs/index.html
Labels: documentation

#105 Enhance README Badges
  README.md
Labels: Readme/Preview, Markdown

#106 Add GTK Installation Support to Setup Script
  install/setup.sh
Labels: enhancement, Bash, Refactor

#107 Refine Installation Guide and Add GTK Setup Instructions
  .github/INSTALLATION.md
Labels: enhancement, Markdown

#108 Update docs for latest installation commit
  docs/index.html
Labels: documentation

#109 Carch GTK
  gtk/carch-gtk.py
  gtk/gtk.sh
Labels: enhancement

#113 Update Markdown Documentation for Docs
  docs/Index/index.md
Labels: documentation, enhancement

#114 Fix Documentation Headings
  docs/index.html
Labels: documentation

#115 Enhance Carch-GTK Interface and Functionality
  gtk/carch-gtk.py
Labels: enhancement, UI, Refactor

#116 Refactor Installation Script
  .gitignore
  build/carch
  cli/carchcli
  cli/carchcli.sh
  install/run.sh
  install/setup.sh
Labels: enhancement, UI, Refactor, Fix Script

#117 Refactor: Core Structure Overhaul
  build/core.sh
Labels: Refactor

#118 Add CLI Commands Guide to Documentation
  docs/index.html
Labels: documentation

#119 Docs: Update Markdown Documentation
  docs/Index/index.md
Labels: documentation

#120 Remove carchscripts.zip in favor of scripts.zip
  source/zip/carchscripts.zip
Labels: enhancement

#123 Refine Carch Documentation
  docs/index.html
Labels: documentation

#124 Add Discord Invite SVG Badge to README
  README.md
Labels: Readme/Preview

#125 Simplify Installation Guide
  .github/INSTALLATION.md
Labels: enhancement, Readme/Preview

#126 Document CLI Changes
  .github/INSTALLATION.md
  docs/Index/index.md
Labels: documentation

#127 Add CLI Guide to Documentation
  docs/index.html
Labels: documentation

#128 Refine readme
  README.md
Labels: Readme/Preview

#131 Comprehensive Updates to Documentation
  docs/.vitepress/config.ts
  docs/acknowledgment/inspiration.md
  docs/contact.md
  docs/get-started.md
  docs/installation/cli.md
  docs/repository/structure.md
Labels: documentation

#132 README Refinement
  README.md
Labels: documentation, enhancement, Readme/Preview, Markdown

#133 Add a note in readme
  README.md
Labels: documentation, Readme/Preview, Markdown

#134 Fix broken image link
  docs/installation/aur.md
  docs/installation/gtk.md
Labels: documentation, enhancement, Markdown

#136 Refactor Documentation for Improved Visual Appeal
  docs/.vitepress/config.ts
  docs/.vitepress/theme/custom.css
  docs/.vitepress/theme/index.ts
  docs/acknowledgment/contributors.md
  docs/acknowledgment/inspiration.md
  docs/github/contributing.md
  docs/index.md
  docs/installation/aur.md
  docs/installation/cli.md
  docs/installation/gtk.md
  docs/scripts/scripts.md
  package.json
Labels: documentation

#137 Making readable readme again
  README.md
Labels: enhancement, Readme/Preview, Markdown

#138 Enhance Documentation with Beautiful Updates
  docs/get-started.md
  docs/getting-started/introduction.md
  docs/index.md
  docs/installation/aur.md
  docs/installation/cli.md
  docs/installation/cmd.md
  docs/installation/gtk.md
Labels: documentation, enhancement, Markdown, UI

#139 Apache 2.0 License
  LICENSE
Labels: Fixes

#140 Enhance Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Markdown, Fixes

#141 Refactor Documentation & Some Fixes
  docs/.vitepress/config.ts
  docs/.vitepress/theme/custom.css
  docs/index.md
Labels: documentation, enhancement

#142 Remove Transparency from Top Section
  docs/index.md
Labels: documentation

#143 Enhancement on docs
  docs/.vitepress/config.ts
  docs/getting-started/introduction.md
  docs/index.md
Labels: documentation

#145 Fix image width to '150'
  docs/index.md
Labels: documentation
