Repository harilvfs/carch, pull requests merged in 2024-12, with the labels that each got.

#146 Create Changelog for Carch
  CHANGELOG.md
Labels: enhancement, Markdown

#148 Update CHANGELOG.md for v3.0.9
  CHANGELOG.md
Labels: enhancement, Markdown

#149 Update PKGBUILD v3.0.9
  PKGBUILD
Labels: enhancement, else

#150 Add Changelog to Top Navigation [Docs]
  docs/.vitepress/config.ts
Labels: documentation

#151 Add Carch Version Info [Docs]
  docs/.vitepress/config.ts
Labels: documentation

#152 Link Changelog to Each Release Tag
  CHANGELOG.md
Labels: enhancement, Markdown

#153 Update Carch to v3.0.9
  build/carch
  build/core.sh
Labels: enhancement

#154 Update GTK to v3.0.9
  gtk/carch-gtk.py
Labels: updates

#155 Add CarchCLI Installation Guide [Docs]
  docs/installation/cmd.md
Labels: documentation, updates

#156 Remove /bin Scripts [Unnecessary]
  bin/clean.sh
  bin/cleanrun.sh
Labels: enhancement, Refactor, Fixes

#157 Refinements to Documentation
  docs/.vitepress/config.ts
  docs/contact.md
  docs/index.md
Labels: documentation, enhancement, Markdown

#158 Add terminal installation to packages script
  scripts/Packages.sh
Labels: enhancement, updates, Bash

#159 Remove last script tracking from core
  build/core.sh
Labels: enhancement, updates, UI, Bash

#160 Update binary build to latest version
  build/carch
  source/zip/scripts.zip
Labels: updates

#161 SHA256 Checksum Verification Passed
  PKGBUILD
Labels: updates

#162 Update: Enhance CLI Installation Tip Section
  docs/installation/cli.md
Labels: documentation, updates

#163 Update .gitignore to Exclude Binary Files
  .gitignore
  PKGBUILD
  build/carch
  cli/carchcli
  gtk/carch-gtk
  source/zip/scripts.zip
Labels: enhancement, updates

#165 Remove Unused 'aboutinfo' Markdown from [docs]
  docs/about.md
Labels: documentation, updates

#166 Design Carch Banner
  README.md
  source/carch.webp
Labels: enhancement, Readme/Preview

#167 Add Penguin Img Src
  README.md
Labels: Readme/Preview, Markdown

#168 Bring Back Imp Stuffs
  .gitignore
  PKGBUILD
  source/zip/scripts.zip
Labels: Zip, updates

#169 Enhanced README with Catppuccin-themed badges
  README.md
Labels: Readme/Preview

#170 Astal Vitepress CSS [Index]
  docs/.vitepress/config.ts
  docs/.vitepress/theme/custom.css
  docs/index.md
  docs/public/package.png
Labels: documentation, enhancement, updates

#171 Update to GPL 3.0 License [Docs]
  docs/.vitepress/config.ts
Labels: documentation

#172 Fix and Update AUR Package Build [ docs ]
  docs/installation/aur.md
Labels: documentation, enhancement, Fixes

#173 Transfer Docs to Carch-Org Repository
  .github/workflows/docs.yml
  docs/.vitepress/config.ts
  docs/.vitepress/theme/custom.css
  docs/.vitepress/theme/index.ts
  docs/acknowledgment/contributors.md
  docs/acknowledgment/inspiration.md
  docs/getting-started/introduction.md
  docs/getting-started/preview.md
  docs/github/codeofconduct.md
  docs/github/contributing.md
  docs/github/roadmap.md
  docs/index.md
  docs/installation/aur.md
  docs/installation/cli.md
  docs/installation/cmd.md
  docs/installation/gtk.md
  docs/public/archlinux-original.svg
  docs/public/archx.png
  docs/public/carchv3.0.gif
  docs/public/package.png
  docs/public/penguin.webp
  docs/scripts/scripts.md
  package-lock.json
  package.json
  source/arch.webp
  source/archx.webp
  source/carchv3.0.gif
  source/penguin.webp
Labels: documentation, enhancement

#175 Update Transferd Documentation Link in README
  README.md
Labels: documentation, Markdown

#176 Change `core.sh` To Carch [ No Binary ] 🪶
  .gitignore
  build/carch
Labels: enhancement, Fixes

#177 Move Cli From [ Binary ] `Bash` Script
  .gitignore
  cli/carchcli
Labels: enhancement, Fixes

#178 From Binary To `Gtk` Bash Script 📜
  .gitignore
  gtk/carch-gtk
Labels: enhancement, Fixes

#179 Fix Script Detection and Bugs
  install/setup.sh
Labels: enhancement, Fixes

#180 Script Zip Changes To Latest Commit 📂
  source/zip/scripts.zip
Labels: Zip

#181 Transfer `Contrib` `Install` `Roadmap` To [Docs] ✈️
  .github/CONTRIBUTING.md
  .github/INSTALLATION.md
  .github/ROADMAP.md
Labels: remove

#183 Add Gum Spin To `Hyprland` Script
  scripts/Hyprland.sh
Labels: enhancement

#184 Bump `v3.0.9` To `v4.0.0`
  build/carch
Labels: updates

#185 CHANGELOG From `v3.0.9` To `v4.0.0`
  CHANGELOG.md
Labels: updates, Markdown

#187 Fix `SDDM` Theme Dir [Scripts]
  scripts/Sddm.sh
Labels: bug, Fixes

#189 Fix Carch `Installation` ⛓️
  install/run.sh
  install/setup.sh
Labels: enhancement, updates, Bash, Fixes

#190 Fix Gum Bug 🐛 [Package Script]
  scripts/Packages.sh
Labels: bug

#191 Add Returing To Menu [Back]
  build/carch
Labels: enhancement, updates

#192 Include `GTK` & `CLI` [Main Script]
  build/carch
Labels: enhancement, updates, UI, Bash, Refactor

#194 Fix Script [DIR]
  gtk/carch-gtk.py
Labels: bug

#195 Remove CLI/GTK As Include [Main Script]
  install/setup.sh
Labels: remove, Bash

#196 Refactor Setup Script
  install/setup.sh
Labels: Bash, Refactor

#197 Refactor Installation Script
  install/run.sh
  install/setup.sh
Labels: Bash, Refactor

#198 Refactor Whole Scripts [Carch]
  scripts/Alacritty.sh
  scripts/Aur.sh
  scripts/Dwm.sh
  scripts/Fastfetch.sh
  scripts/Fonts.sh
  scripts/Grub.sh
  scripts/Hyprland.sh
  scripts/Kitty.sh
  scripts/LTS-Kernal.sh
  scripts/Neovim.sh
  scripts/Packages.sh
  scripts/Picom.sh
  scripts/Rofi.sh
  scripts/Sddm.sh
  scripts/SwayWM.sh
  scripts/Themes-Icons.sh
  scripts/Wallpapers.sh
  scripts/i3wm.sh
Labels: Bash, Refactor

#200 man-page for [Carch] 📄
  man/carch.1
Labels: updates

#201 Update Script for Man Pages Handling
  install/run.sh
  install/setup.sh
Labels: updates

#203 Bump Version 4.1.0
  build/carch
  gtk/carch-gtk.py
  install/setup.sh
Labels: updates

#204 4.1.0 CHANGELOG
  CHANGELOG.md
Labels: Markdown

#205 Add AUR Update Note [CHANGELOG v4.1.0]
  CHANGELOG.md
Labels: updates

#206 Add [Logging] Carch
  build/carch
Labels: updates, Bash, Refactor

#207 Add logging `Carch` [GTK]
  gtk/carch-gtk.py
Labels: enhancement, updates, feature

#208 Making Script Clean 🧹
  install/run.sh
Labels: enhancement

#209 Making Setup Installation `clean` 🧹
  install/setup.sh
Labels: enhancement

#210 Script Fixes [BUG]
  .github/workflows/zip.yml
  scripts/Alacritty.sh
  scripts/Aur.sh
  scripts/Dwm.sh
  scripts/Fonts.sh
  scripts/Hyprland.sh
  scripts/Neovim.sh
  scripts/Picom.sh
  scripts/Sddm.sh
  scripts/SwayWM.sh
  scripts/i3wm.sh
Labels: bug, enhancement

#211 Add Carch Icons [Desktop Entry]
  carch.desktop
Labels: enhancement, updates

#212 Added Icon For Desktop Entry
  install/setup.sh
Labels: enhancement, Bash

#213 Add Uninstall Command [Carch]
  build/carch
Labels: enhancement, Bash

#214 Add Some Packages [Package Script]
  scripts/Packages.sh
Labels: enhancement, Bash

#215 Added Useful Command [Carch --[options]]
  build/carch
Labels: enhancement, updates, feature, Bash

#216 Config File Example
  config/carch.conf
Labels: custom

#217 Auto Completions [`Bash` `Zsh`]
  completions/bash/carch
  completions/zsh/_carch
Labels: custom

#218 Fish Completions [Added]
  completions/fish/carch.fish
Labels: enhancement, custom, feature

#219 Added Commands Completions [ZSH BASH FISH]
  install/setup.sh
Labels: feature, Bash

#220 Add Completions To Uninstall [Command]
  build/carch
Labels: Bash

#221 Upgrade Version 4.1.1
  build/carch
  gtk/carch-gtk.py
  install/setup.sh
  man/carch.1
Labels: updates

#222 Fix Completions Removel
  build/carch
  install/setup.sh
Labels: Bash, Fixes

#224 Minor Fish Dir Fixes
  build/carch
  install/setup.sh
Labels: Fixes
