Repository harilvfs/carch, pull requests merged in 2025-06, with the labels that each got.

#471 docs(update): redoing whole readme
  .github/README.ar.md
  .github/README.de.md
  .github/README.es.md
  .github/README.fr.md
  .github/README.hi.md
  .github/README.ko.md
  .github/README.md
  .github/README.ne.md
  .github/README.ru.md
  .github/README.zh.md
  .github/workflows/check-pr.yml
Labels: documentation

#485 chore(script): remove comments
  scripts/cleanup.sh
Labels: remove

#489 chore: update project description
  Cargo.toml
  carch.desktop
  man/carch.1
  scripts/install.sh
Labels: documentation

#493 docs(readme): add preview
  .github/README.md
Labels: documentation

#499 feat(installer): rewrite install script in Go
  .gitignore
  scripts/install/Makefile
  scripts/install/go.mod
  scripts/install/go.sum
  scripts/install/install.go
  scripts/install/main.go
  scripts/install/uninstall.go
  scripts/install/update.go
  scripts/install/utils.go
Labels: refactor
