Repository harilvfs/carch, pull requests merged in 2025-08, with the labels that each got.

#548 refactor(scripts): centralize distro detection and simplify scripts
  scripts/modules/Desktop/Bspwm.sh
  scripts/modules/Desktop/Dunst.sh
  scripts/modules/Desktop/Dwm.sh
  scripts/modules/Desktop/Hyprland.sh
  scripts/modules/Desktop/Picom.sh
  scripts/modules/Desktop/Rofi.sh
  scripts/modules/Desktop/Themes-Icons.sh
  scripts/modules/Development/Bun.sh
  scripts/modules/Development/Helix.sh
  scripts/modules/Development/Neovim.sh
  scripts/modules/Development/Npm.sh
  scripts/modules/System/Audio.sh
  scripts/modules/System/Aur.sh
  scripts/modules/System/Bluetooth.sh
  scripts/modules/System/Brightness.sh
  scripts/modules/System/Chaotic-Aur.sh
  scripts/modules/System/Fastfetch.sh
  scripts/modules/System/Fonts.sh
  scripts/modules/System/LTS-Kernel.sh
  scripts/modules/System/Packages.sh
  scripts/modules/System/Sddm.sh
  scripts/modules/System/packages/Packages-Android.sh
  scripts/modules/System/packages/Packages-Browsers.sh
  scripts/modules/System/packages/Packages-Communication.sh
  scripts/modules/System/packages/Packages-Crypto-Tools.sh
  scripts/modules/System/packages/Packages-Development.sh
  scripts/modules/System/packages/Packages-Editing.sh
  scripts/modules/System/packages/Packages-FM-Tools.sh
  scripts/modules/System/packages/Packages-FileManagers.sh
  scripts/modules/System/packages/Packages-Gaming.sh
  scripts/modules/System/packages/Packages-GitHub.sh
  scripts/modules/System/packages/Packages-Multimedia.sh
  scripts/modules/System/packages/Packages-Music.sh
  scripts/modules/System/packages/Packages-Productivity.sh
  scripts/modules/System/packages/Packages-Streaming.sh
  scripts/modules/System/packages/Packages-Terminals.sh
  scripts/modules/System/packages/Packages-TextEditors.sh
  scripts/modules/System/packages/Packages-Virtualization.sh
  scripts/modules/Terminal/Alacritty.sh
  scripts/modules/Terminal/Bash.sh
  scripts/modules/Terminal/Fish.sh
  scripts/modules/Terminal/Foot.sh
  scripts/modules/Terminal/Ghostty.sh
  scripts/modules/Terminal/Kitty.sh
  scripts/modules/Terminal/Tmux.sh
  scripts/modules/Terminal/Zsh.sh
  scripts/modules/detect-distro.sh
Labels: enhancement, UI/UX, refactor

#552 refactor(scripts): using function call
  scripts/modules/Desktop/Dunst.sh
  scripts/modules/Desktop/Wallpapers.sh
  scripts/modules/Development/Npm.sh
  scripts/modules/Packages/Android-Tools.sh
  scripts/modules/Packages/Browsers.sh
  scripts/modules/Packages/Communication.sh
  scripts/modules/Packages/Crypto-Tools.sh
  scripts/modules/Packages/Development-Tools.sh
  scripts/modules/Packages/Editing.sh
  scripts/modules/Packages/FM-Tools.sh
  scripts/modules/Packages/FileManagers.sh
  scripts/modules/Packages/Gaming.sh
  scripts/modules/Packages/GitHub.sh
  scripts/modules/Packages/Multimedia.sh
  scripts/modules/Packages/Music.sh
  scripts/modules/Packages/Productivity.sh
  scripts/modules/Packages/Streaming.sh
  scripts/modules/Packages/Terminals.sh
  scripts/modules/Packages/TextEditors.sh
  scripts/modules/Packages/Virtualization.sh
  scripts/modules/System/Grub.sh
  scripts/modules/Terminal/Bash.sh
  scripts/modules/Terminal/Fish.sh
  scripts/modules/Terminal/Kitty.sh
  scripts/modules/Terminal/Tmux.sh
  scripts/modules/Terminal/Zsh.sh
Labels: refactor

#553 style(script): using same styling across all scripts
  .github/workflows/shellfmt.yml
  scripts/modules/Desktop/Bspwm.sh
  scripts/modules/Desktop/Dunst.sh
  scripts/modules/Desktop/Dwm.sh
  scripts/modules/Desktop/Hyprland.sh
  scripts/modules/Desktop/Picom.sh
  scripts/modules/Desktop/Rofi.sh
  scripts/modules/Desktop/Themes-Icons.sh
  scripts/modules/Desktop/Wallpapers.sh
  scripts/modules/Development/Bun.sh
  scripts/modules/Development/Helix.sh
  scripts/modules/Development/Neovim.sh
  scripts/modules/Development/Npm.sh
  scripts/modules/Packages/Streaming.sh
  scripts/modules/System/Audio.sh
  scripts/modules/System/Aur.sh
  scripts/modules/System/AutoLogin-TTY.sh
  scripts/modules/System/Bluetooth.sh
  scripts/modules/System/Brightness.sh
  scripts/modules/System/Chaotic-Aur.sh
  scripts/modules/System/Fastfetch.sh
  scripts/modules/System/Fonts.sh
  scripts/modules/System/Grub.sh
  scripts/modules/System/LTS-Kernel.sh
  scripts/modules/System/Sddm.sh
  scripts/modules/Terminal/Alacritty.sh
  scripts/modules/Terminal/Bash.sh
  scripts/modules/Terminal/Fish.sh
  scripts/modules/Terminal/Foot.sh
  scripts/modules/Terminal/Ghostty.sh
  scripts/modules/Terminal/Kitty.sh
  scripts/modules/Terminal/Tmux.sh
  scripts/modules/Terminal/Zsh.sh
  scripts/modules/packages.sh
  scripts/modules/shfmt.sh
Labels: enhancement, UI/UX

#557 docs(readme): use mainstream ImgShield Ratatui badge
  .github/README.md
Labels: documentation

#558 docs(readme): use same style badge as Ratatui
  .github/README.md
Labels: documentation
