Repository harilvfs/carch, pull requests merged in 2025-07, with the labels that each got.

#515 refactor(ui): new tui design
  src/ui/app.rs
  src/ui/popups.rs
  src/ui/render.rs
Labels: UI/UX, refactor, rust

#524 feat: initial support for opensuse
  .github/ISSUE_TEMPLATE/bug-reports.yml
  .github/ISSUE_TEMPLATE/feature-reqests.yml
  .github/PULL_REQUEST_TEMPLATE.md
  src/modules/Desktop/Dunst.sh
  src/modules/Desktop/Dwm.sh
  src/modules/Desktop/Hyprland.sh
  src/modules/Desktop/Picom.sh
  src/modules/Desktop/Rofi.sh
  src/modules/Desktop/Themes-Icons.sh
  src/modules/Desktop/Wallpapers.sh
  src/modules/Development/Bun.sh
  src/modules/Development/Helix.sh
  src/modules/Development/Neovim.sh
  src/modules/Development/Npm.sh
  src/modules/System/Audio.sh
  src/modules/System/Aur.sh
  src/modules/System/Bluetooth.sh
  src/modules/System/Brightness.sh
  src/modules/System/Chaotic-Aur.sh
  src/modules/System/Fastfetch.sh
  src/modules/System/Fonts.sh
  src/modules/System/LTS-Kernel.sh
  src/modules/System/Packages.sh
  src/modules/System/Sddm.sh
  src/modules/System/packages/Packages-Android.sh
  src/modules/System/packages/Packages-Browsers.sh
  src/modules/System/packages/Packages-Communication.sh
  src/modules/System/packages/Packages-Crypto-Tools.sh
  src/modules/System/packages/Packages-Development.sh
  src/modules/System/packages/Packages-Editing.sh
  src/modules/System/packages/Packages-FM-Tools.sh
  src/modules/System/packages/Packages-FileManagers.sh
  src/modules/System/packages/Packages-Gaming.sh
  src/modules/System/packages/Packages-Multimedia.sh
  src/modules/System/packages/Packages-Music.sh
  src/modules/System/packages/Packages-Productivity.sh
  src/modules/System/packages/Packages-Streaming.sh
  src/modules/System/packages/Packages-Terminals.sh
  src/modules/System/packages/Packages-TextEditors.sh
  src/modules/System/packages/Packages-Virtualization.sh
  src/modules/Terminal/Alacritty.sh
  src/modules/Terminal/Bash.sh
  src/modules/Terminal/Fish.sh
  src/modules/Terminal/Foot.sh
  src/modules/Terminal/Ghostty.sh
  src/modules/Terminal/Kitty.sh
  src/modules/Terminal/Tmux.sh
  src/modules/Terminal/Zsh.sh
Labels: enhancement, update

#536 refactor: document rust code
  src/args.rs
  src/commands.rs
  src/error.rs
  src/main.rs
  src/ui/actions.rs
  src/ui/app.rs
  src/ui/events.rs
  src/ui/popups/confirmation.rs
  src/ui/popups/help.rs
  src/ui/popups/preview.rs
  src/ui/popups/run_script.rs
  src/ui/popups/search.rs
  src/ui/render.rs
  src/ui/state.rs
  src/ui/system_info.rs
  src/ui/widgets/category_list.rs
  src/ui/widgets/header.rs
  src/ui/widgets/script_list.rs
  src/ui/widgets/status_bar.rs
Labels: documentation, refactor, rust

#537 feat: add description functionality for scripts
  Cargo.lock
  Cargo.toml
  src/error.rs
  src/main.rs
  src/modules/Browser/desc.toml
  src/modules/Desktop/desc.toml
  src/modules/Development/desc.toml
  src/modules/System/desc.toml
  src/modules/Terminal/desc.toml
  src/ui/actions.rs
  src/ui/app.rs
  src/ui/events.rs
  src/ui/popups/confirmation.rs
  src/ui/popups/description.rs
  src/ui/popups/help.rs
  src/ui/popups/mod.rs
  src/ui/popups/preview.rs
  src/ui/popups/run_script.rs
  src/ui/popups/search.rs
  src/ui/render.rs
  src/ui/state.rs
  src/ui/widgets/category_list.rs
  src/ui/widgets/header.rs
  src/ui/widgets/status_bar.rs
Labels: enhancement, rust

#542 feat(commands): add cli commands for theme selection
  Cargo.lock
  completions/bash/carch
  completions/fish/carch.fish
  completions/zsh/_carch
  man/carch.1
  src/args.rs
  src/main.rs
  src/ui/app.rs
  src/ui/events.rs
  src/ui/state.rs
  xtask/Cargo.toml
  xtask/src/args.rs
  xtask/src/main.rs
Labels: enhancement, refactor

#543 chore: remove bacon
  bacon.toml
Labels: remove

#544 docs(readme): add catppuccin footer
  .github/README.md
Labels: documentation
