Repository harilvfs/carch, pull requests merged in 2025-05, with the labels that each got.

#435 Changelog v4.4.2
  CHANGELOG.md
Labels: documentation

#439 Changelog v4.4.3
  CHANGELOG.md
Labels: documentation

#441 Changelog v4.4.4
  CHANGELOG.md
Labels: documentation

#447 feat: add extension script & structure changes
  src/modules/Browser/Extensions.sh
  src/modules/Desktop/Dunst.sh
  src/modules/Desktop/Dwm.sh
  src/modules/Desktop/Hyprland.sh
  src/modules/Desktop/Picom.sh
  src/modules/Desktop/Rofi.sh
  src/modules/Desktop/SwayWM.sh
  src/modules/Desktop/Themes-Icons.sh
  src/modules/Desktop/Wallpapers.sh
  src/modules/Desktop/i3wm.sh
  src/modules/Development/Bun.sh
  src/modules/Development/Helix.sh
  src/modules/Development/Neovim.sh
  src/modules/Development/Npm.sh
  src/modules/System/Audio.sh
  src/modules/System/Aur.sh
  src/modules/System/Bluetooth.sh
  src/modules/System/Brightness.sh
  src/modules/System/Chaotic-Aur.sh
  src/modules/System/Fastfetch.sh
  src/modules/System/Fonts.sh
  src/modules/System/Grub.sh
  src/modules/System/LTS-Kernel.sh
  src/modules/System/Packages.sh
  src/modules/System/Sddm.sh
  src/modules/Terminal/Alacritty.sh
  src/modules/Terminal/Bash.sh
  src/modules/Terminal/Fish.sh
  src/modules/Terminal/Foot.sh
  src/modules/Terminal/Ghostty.sh
  src/modules/Terminal/Kitty.sh
  src/modules/Terminal/Tmux.sh
  src/modules/Terminal/Zsh.sh
Labels: enhancement

#448 Changelog v4.4.5
  CHANGELOG.md
Labels: documentation

#453 Changelog v4.4.7
  CHANGELOG.md
Labels: documentation

#456 feat: add defaulting option to [ zsh bash ] scripts
  src/modules/Terminal/Bash.sh
  src/modules/Terminal/Zsh.sh
Labels: enhancement

#457 docs: minor improvement to markdown side
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#459 docs: redoing the readme part
  .github/README.hi.md
  .github/README.md
  .github/README.np.md
Labels: documentation

#464 rust: rounded script list & help [ ui ]
  src/display.rs
  src/script_list.rs
Labels: rust
